// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnBsO6TtsM41rht1N4ZuW-bGDuMCBylz0',
    appId: '1:207585441824:web:eb22d65fb28bc7ee06e445',
    messagingSenderId: '207585441824',
    projectId: 'chatusers-9417f',
    authDomain: 'chatusers-9417f.firebaseapp.com',
    storageBucket: 'chatusers-9417f.appspot.com',
    measurementId: 'G-ZTJV311PNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWJLQFeu_Luq0OgjlVFZIjM6xgMtDcyU',
    appId: '1:207585441824:android:6e8aa3b7e01f7f8006e445',
    messagingSenderId: '207585441824',
    projectId: 'chatusers-9417f',
    storageBucket: 'chatusers-9417f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2qt3OiQTkQzj_0LtisFvsAQfJpt0DP0',
    appId: '1:207585441824:ios:9c5631a1b4ee091d06e445',
    messagingSenderId: '207585441824',
    projectId: 'chatusers-9417f',
    storageBucket: 'chatusers-9417f.appspot.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR2qt3OiQTkQzj_0LtisFvsAQfJpt0DP0',
    appId: '1:207585441824:ios:04271e015d3fb21406e445',
    messagingSenderId: '207585441824',
    projectId: 'chatusers-9417f',
    storageBucket: 'chatusers-9417f.appspot.com',
    iosBundleId: 'com.example.capstoneProject.RunnerTests',
  );
}
